services:
  db-test:
    image: postgres:latest
    container_name: fastapi-boilerplate-db-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # pragma: allowlist secret
      POSTGRES_DB: fastapi_db_test
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql
