"""
Seed script to populate initial roles.
Permissions are now automatically generated by the app's lifespan on startup.

Run with: poetry run python -m app.scripts.seed_roles
"""

import asyncio

from sqlalchemy import select

from app.domain.auth.model import Permission, Role, role_permissions
from app.infrastructure.db.session import AsyncSessionLocal

# Define roles and their permissions
ROLES = {
    "admin": {
        "description": "Administrator with full access",
        "permissions": "*",  # All permissions dynamically assigned
    },
    "user": {
        "description": "Regular user with limited access",
        "permissions": ["user:read"],
    },
}


async def seed_roles():
    """Create initial roles and assign existing permissions."""
    async with AsyncSessionLocal() as db:
        # Check if already seeded
        result = await db.execute(select(Role))
        if result.scalars().first():
            print("✓ Roles already seeded")
            return

        # Fetch all auto-generated permissions
        perm_result = await db.execute(select(Permission))
        all_permissions = perm_result.scalars().all()
        
        if not all_permissions:
            print("No permissions found. Ensure the app has been started at least once to auto-sync.")
            return

        # Create roles and assign permissions
        for role_name, role_config in ROLES.items():
            role = Role(
                name=role_name,
                description=role_config["description"],
            )
            db.add(role)
            await db.flush()

            # Assign permissions
            if role_config["permissions"] == "*":
                # Assign all absolute permissions fetched from DB
                perm_ids = [p.id for p in all_permissions]
            else:
                # Assign specific permissions
                perm_ids = [
                    p.id for p in all_permissions
                    if p.code in role_config["permissions"]
                ]

            if perm_ids:
                await db.execute(
                    role_permissions.insert().values(
                        [{"role_id": role.id, "permission_id": pid} for pid in perm_ids]
                    )
                )

        await db.commit()
        print("Roles seeded successfully")
        print(f"  - Created {len(ROLES)} roles")

if __name__ == "__main__":
    asyncio.run(seed_roles())
